using System.Collections.Generic;

namespace Colibri.Helpers
{
    public static class Smiles
    {
        public static Dictionary<string, string> Base = new Dictionary<string, string>()
        {
          {
            "\xD83D\xDE0A",
            "D83DDE0A"
          },
          {
            "\xD83D\xDE03",
            "D83DDE03"
          },
          {
            "\xD83D\xDE09",
            "D83DDE09"
          },
          {
            "\xD83D\xDE06",
            "D83DDE06"
          },
          {
            "\xD83D\xDE1C",
            "D83DDE1C"
          },
          {
            "\xD83D\xDE0B",
            "D83DDE0B"
          },
          {
            "\xD83D\xDE0D",
            "D83DDE0D"
          },
          {
            "\xD83D\xDE0E",
            "D83DDE0E"
          },
          {
            "\xD83D\xDE12",
            "D83DDE12"
          },
          {
            "\xD83D\xDE0F",
            "D83DDE0F"
          },
          {
            "\xD83D\xDE14",
            "D83DDE14"
          },
          {
            "\xD83D\xDE22",
            "D83DDE22"
          },
          {
            "\xD83D\xDE2D",
            "D83DDE2D"
          },
          {
            "\xD83D\xDE29",
            "D83DDE29"
          },
          {
            "\xD83D\xDE28",
            "D83DDE28"
          },
          {
            "\xD83D\xDE10",
            "D83DDE10"
          },
          {
            "\xD83D\xDE0C",
            "D83DDE0C"
          },
          {
            "\xD83D\xDE04",
            "D83DDE04"
          },
          {
            "\xD83D\xDE07",
            "D83DDE07"
          },
          {
            "\xD83D\xDE30",
            "D83DDE30"
          },
          {
            "\xD83D\xDE32",
            "D83DDE32"
          },
          {
            "\xD83D\xDE33",
            "D83DDE33"
          },
          {
            "\xD83D\xDE37",
            "D83DDE37"
          },
          {
            "\xD83D\xDE02",
            "D83DDE02"
          },
          {
            "❤",
            "2764"
          },
          {
            "\xD83D\xDE1A",
            "D83DDE1A"
          },
          {
            "\xD83D\xDE15",
            "D83DDE15"
          },
          {
            "\xD83D\xDE2F",
            "D83DDE2F"
          },
          {
            "\xD83D\xDE26",
            "D83DDE26"
          },
          {
            "\xD83D\xDE35",
            "D83DDE35"
          },
          {
            "\xD83D\xDE20",
            "D83DDE20"
          },
          {
            "\xD83D\xDE21",
            "D83DDE21"
          },
          {
            "\xD83D\xDE1D",
            "D83DDE1D"
          },
          {
            "\xD83D\xDE34",
            "D83DDE34"
          },
          {
            "\xD83D\xDE18",
            "D83DDE18"
          },
          {
            "\xD83D\xDE1F",
            "D83DDE1F"
          },
          {
            "\xD83D\xDE2C",
            "D83DDE2C"
          },
          {
            "\xD83D\xDE36",
            "D83DDE36"
          },
          {
            "\xD83D\xDE2A",
            "D83DDE2A"
          },
          {
            "\xD83D\xDE2B",
            "D83DDE2B"
          },
          {
            "☺",
            "263A"
          },
          {
            "\xD83D\xDE00",
            "D83DDE00"
          },
          {
            "\xD83D\xDE25",
            "D83DDE25"
          },
          {
            "\xD83D\xDE1B",
            "D83DDE1B"
          },
          {
            "\xD83D\xDE16",
            "D83DDE16"
          },
          {
            "\xD83D\xDE24",
            "D83DDE24"
          },
          {
            "\xD83D\xDE23",
            "D83DDE23"
          },
          {
            "\xD83D\xDE27",
            "D83DDE27"
          },
          {
            "\xD83D\xDE11",
            "D83DDE11"
          },
          {
            "\xD83D\xDE05",
            "D83DDE05"
          },
          {
            "\xD83D\xDE2E",
            "D83DDE2E"
          },
          {
            "\xD83D\xDE1E",
            "D83DDE1E"
          },
          {
            "\xD83D\xDE19",
            "D83DDE19"
          },
          {
            "\xD83D\xDE13",
            "D83DDE13"
          },
          {
            "\xD83D\xDE01",
            "D83DDE01"
          },
          {
            "\xD83D\xDE31",
            "D83DDE31"
          },
          {
            "\xD83D\xDE08",
            "D83DDE08"
          },
          {
            "\xD83D\xDC7F",
            "D83DDC7F"
          },
          {
            "\xD83D\xDC7D",
            "D83DDC7D"
          },
          {
            "\xD83D\xDC4D",
            "D83DDC4D"
          },
          {
            "\xD83D\xDC4E",
            "D83DDC4E"
          },
          {
            "☝",
            "261D"
          },
          {
            "✌",
            "270C"
          },
          {
            "\xD83D\xDC4C",
            "D83DDC4C"
          },
          {
            "\xD83D\xDC4F",
            "D83DDC4F"
          },
          {
            "\xD83D\xDC4A",
            "D83DDC4A"
          },
          {
            "✋",
            "270B"
          },
          {
            "\xD83D\xDE4F",
            "D83DDE4F"
          },
          {
            "\xD83D\xDC43",
            "D83DDC43"
          },
          {
            "\xD83D\xDC46",
            "D83DDC46"
          },
          {
            "\xD83D\xDC47",
            "D83DDC47"
          },
          {
            "\xD83D\xDC48",
            "D83DDC48"
          },
          {
            "\xD83D\xDCAA",
            "D83DDCAA"
          },
          {
            "\xD83D\xDC42",
            "D83DDC42"
          },
          {
            "\xD83D\xDC8B",
            "D83DDC8B"
          },
          {
            "\xD83D\xDCA9",
            "D83DDCA9"
          },
          {
            "❄",
            "2744"
          },
          {
            "\xD83C\xDF4A",
            "D83CDF4A"
          },
          {
            "\xD83C\xDF77",
            "D83CDF77"
          },
          {
            "\xD83C\xDF78",
            "D83CDF78"
          },
          {
            "\xD83C\xDF85",
            "D83CDF85"
          },
          {
            "\xD83D\xDCA6",
            "D83DDCA6"
          },
          {
            "\xD83D\xDC7A",
            "D83DDC7A"
          },
          {
            "\xD83D\xDC28",
            "D83DDC28"
          },
          {
            "\xD83D\xDD1E",
            "D83DDD1E"
          },
          {
            "\xD83D\xDC79",
            "D83DDC79"
          },
          {
            "⚽",
            "26BD"
          },
          {
            "⛅",
            "26C5"
          },
          {
            "\xD83C\xDF1F",
            "D83CDF1F"
          },
          {
            "\xD83C\xDF4C",
            "D83CDF4C"
          },
          {
            "\xD83C\xDF7A",
            "D83CDF7A"
          },
          {
            "\xD83C\xDF7B",
            "D83CDF7B"
          },
          {
            "\xD83C\xDF39",
            "D83CDF39"
          },
          {
            "\xD83C\xDF45",
            "D83CDF45"
          },
          {
            "\xD83C\xDF52",
            "D83CDF52"
          },
          {
            "\xD83C\xDF81",
            "D83CDF81"
          },
          {
            "\xD83C\xDF82",
            "D83CDF82"
          },
          {
            "\xD83C\xDF84",
            "D83CDF84"
          },
          {
            "\xD83C\xDFC1",
            "D83CDFC1"
          },
          {
            "\xD83C\xDFC6",
            "D83CDFC6"
          },
          {
            "\xD83D\xDC0E",
            "D83DDC0E"
          },
          {
            "\xD83D\xDC0F",
            "D83DDC0F"
          },
          {
            "\xD83D\xDC1C",
            "D83DDC1C"
          },
          {
            "\xD83D\xDC2B",
            "D83DDC2B"
          },
          {
            "\xD83D\xDC2E",
            "D83DDC2E"
          },
          {
            "\xD83D\xDC03",
            "D83DDC03"
          },
          {
            "\xD83D\xDC3B",
            "D83DDC3B"
          },
          {
            "\xD83D\xDC3C",
            "D83DDC3C"
          },
          {
            "\xD83D\xDC05",
            "D83DDC05"
          },
          {
            "\xD83D\xDC13",
            "D83DDC13"
          },
          {
            "\xD83D\xDC18",
            "D83DDC18"
          },
          {
            "\xD83D\xDC94",
            "D83DDC94"
          },
          {
            "\xD83D\xDCAD",
            "D83DDCAD"
          },
          {
            "\xD83D\xDC36",
            "D83DDC36"
          },
          {
            "\xD83D\xDC31",
            "D83DDC31"
          },
          {
            "\xD83D\xDC37",
            "D83DDC37"
          },
          {
            "\xD83D\xDC11",
            "D83DDC11"
          },
          {
            "⏳",
            "23F3"
          },
          {
            "⚾",
            "26BE"
          },
          {
            "⛄",
            "26C4"
          },
          {
            "☀",
            "2600"
          },
          {
            "\xD83C\xDF3A",
            "D83CDF3A"
          },
          {
            "\xD83C\xDF3B",
            "D83CDF3B"
          },
          {
            "\xD83C\xDF3C",
            "D83CDF3C"
          },
          {
            "\xD83C\xDF3D",
            "D83CDF3D"
          },
          {
            "\xD83C\xDF4B",
            "D83CDF4B"
          },
          {
            "\xD83C\xDF4D",
            "D83CDF4D"
          },
          {
            "\xD83C\xDF4E",
            "D83CDF4E"
          },
          {
            "\xD83C\xDF4F",
            "D83CDF4F"
          },
          {
            "\xD83C\xDF6D",
            "D83CDF6D"
          },
          {
            "\xD83C\xDF37",
            "D83CDF37"
          },
          {
            "\xD83C\xDF38",
            "D83CDF38"
          },
          {
            "\xD83C\xDF46",
            "D83CDF46"
          },
          {
            "\xD83C\xDF49",
            "D83CDF49"
          },
          {
            "\xD83C\xDF50",
            "D83CDF50"
          },
          {
            "\xD83C\xDF51",
            "D83CDF51"
          },
          {
            "\xD83C\xDF53",
            "D83CDF53"
          },
          {
            "\xD83C\xDF54",
            "D83CDF54"
          },
          {
            "\xD83C\xDF55",
            "D83CDF55"
          },
          {
            "\xD83C\xDF56",
            "D83CDF56"
          },
          {
            "\xD83C\xDF57",
            "D83CDF57"
          },
          {
            "\xD83C\xDF69",
            "D83CDF69"
          },
          {
            "\xD83C\xDF83",
            "D83CDF83"
          },
          {
            "\xD83C\xDFAA",
            "D83CDFAA"
          },
          {
            "\xD83C\xDFB1",
            "D83CDFB1"
          },
          {
            "\xD83C\xDFB2",
            "D83CDFB2"
          },
          {
            "\xD83C\xDFB7",
            "D83CDFB7"
          },
          {
            "\xD83C\xDFB8",
            "D83CDFB8"
          },
          {
            "\xD83C\xDFBE",
            "D83CDFBE"
          },
          {
            "\xD83C\xDFC0",
            "D83CDFC0"
          },
          {
            "\xD83C\xDFE6",
            "D83CDFE6"
          },
          {
            "\xD83D\xDE38",
            "D83DDE38"
          },
          {
            "\xD83D\xDE39",
            "D83DDE39"
          },
          {
            "\xD83D\xDE3C",
            "D83DDE3C"
          },
          {
            "\xD83D\xDE3D",
            "D83DDE3D"
          },
          {
            "\xD83D\xDE3E",
            "D83DDE3E"
          },
          {
            "\xD83D\xDE3F",
            "D83DDE3F"
          },
          {
            "\xD83D\xDE3B",
            "D83DDE3B"
          },
          {
            "\xD83D\xDE40",
            "D83DDE40"
          },
          {
            "\xD83D\xDE3A",
            "D83DDE3A"
          },
          {
            "⏰",
            "23F0"
          },
          {
            "☁",
            "2601"
          },
          {
            "☎",
            "260E"
          },
          {
            "☕",
            "2615"
          },
          {
            "♻",
            "267B"
          },
          {
            "⚠",
            "26A0"
          },
          {
            "⚡",
            "26A1"
          },
          {
            "⛔",
            "26D4"
          },
          {
            "⛪",
            "26EA"
          },
          {
            "⛳",
            "26F3"
          },
          {
            "⛵",
            "26F5"
          },
          {
            "⛽",
            "26FD"
          },
          {
            "✂",
            "2702"
          },
          {
            "✈",
            "2708"
          },
          {
            "✉",
            "2709"
          },
          {
            "✊",
            "270A"
          },
          {
            "✏",
            "270F"
          },
          {
            "✒",
            "2712"
          },
          {
            "✨",
            "2728"
          },
          {
            "\xD83C\xDC04",
            "D83CDC04"
          },
          {
            "\xD83C\xDCCF",
            "D83CDCCF"
          },
          {
            "\xD83C\xDD98",
            "D83CDD98"
          },
          {
            "\xD83C\xDF02",
            "D83CDF02"
          },
          {
            "\xD83C\xDF0D",
            "D83CDF0D"
          },
          {
            "\xD83C\xDF1B",
            "D83CDF1B"
          },
          {
            "\xD83C\xDF1D",
            "D83CDF1D"
          },
          {
            "\xD83C\xDF1E",
            "D83CDF1E"
          },
          {
            "\xD83C\xDF30",
            "D83CDF30"
          },
          {
            "\xD83C\xDF31",
            "D83CDF31"
          },
          {
            "\xD83C\xDF32",
            "D83CDF32"
          },
          {
            "\xD83C\xDF33",
            "D83CDF33"
          },
          {
            "\xD83C\xDF34",
            "D83CDF34"
          },
          {
            "\xD83C\xDF35",
            "D83CDF35"
          },
          {
            "\xD83C\xDF3E",
            "D83CDF3E"
          },
          {
            "\xD83C\xDF3F",
            "D83CDF3F"
          },
          {
            "\xD83C\xDF40",
            "D83CDF40"
          },
          {
            "\xD83C\xDF41",
            "D83CDF41"
          },
          {
            "\xD83C\xDF42",
            "D83CDF42"
          },
          {
            "\xD83C\xDF43",
            "D83CDF43"
          },
          {
            "\xD83C\xDF44",
            "D83CDF44"
          },
          {
            "\xD83C\xDF47",
            "D83CDF47"
          },
          {
            "\xD83C\xDF48",
            "D83CDF48"
          },
          {
            "\xD83C\xDF5A",
            "D83CDF5A"
          },
          {
            "\xD83C\xDF5B",
            "D83CDF5B"
          },
          {
            "\xD83C\xDF5C",
            "D83CDF5C"
          },
          {
            "\xD83C\xDF5D",
            "D83CDF5D"
          },
          {
            "\xD83C\xDF5E",
            "D83CDF5E"
          },
          {
            "\xD83C\xDF5F",
            "D83CDF5F"
          },
          {
            "\xD83C\xDF60",
            "D83CDF60"
          },
          {
            "\xD83C\xDF61",
            "D83CDF61"
          },
          {
            "\xD83C\xDF62",
            "D83CDF62"
          },
          {
            "\xD83C\xDF63",
            "D83CDF63"
          },
          {
            "\xD83C\xDF64",
            "D83CDF64"
          },
          {
            "\xD83C\xDF65",
            "D83CDF65"
          },
          {
            "\xD83C\xDF66",
            "D83CDF66"
          },
          {
            "\xD83C\xDF67",
            "D83CDF67"
          },
          {
            "\xD83C\xDF68",
            "D83CDF68"
          },
          {
            "\xD83C\xDF6A",
            "D83CDF6A"
          },
          {
            "\xD83C\xDF6B",
            "D83CDF6B"
          },
          {
            "\xD83C\xDF6C",
            "D83CDF6C"
          },
          {
            "\xD83C\xDF6E",
            "D83CDF6E"
          },
          {
            "\xD83C\xDF6F",
            "D83CDF6F"
          },
          {
            "\xD83C\xDF70",
            "D83CDF70"
          },
          {
            "\xD83C\xDF71",
            "D83CDF71"
          },
          {
            "\xD83C\xDF72",
            "D83CDF72"
          },
          {
            "\xD83C\xDF73",
            "D83CDF73"
          },
          {
            "\xD83C\xDF74",
            "D83CDF74"
          },
          {
            "\xD83C\xDF75",
            "D83CDF75"
          },
          {
            "\xD83C\xDF76",
            "D83CDF76"
          },
          {
            "\xD83C\xDF79",
            "D83CDF79"
          },
          {
            "\xD83C\xDF7C",
            "D83CDF7C"
          },
          {
            "\xD83C\xDF80",
            "D83CDF80"
          },
          {
            "\xD83C\xDF88",
            "D83CDF88"
          },
          {
            "\xD83C\xDF89",
            "D83CDF89"
          },
          {
            "\xD83C\xDF8A",
            "D83CDF8A"
          },
          {
            "\xD83C\xDF8B",
            "D83CDF8B"
          },
          {
            "\xD83C\xDF8C",
            "D83CDF8C"
          },
          {
            "\xD83C\xDF8D",
            "D83CDF8D"
          },
          {
            "\xD83C\xDF8E",
            "D83CDF8E"
          },
          {
            "\xD83C\xDF8F",
            "D83CDF8F"
          },
          {
            "\xD83C\xDF90",
            "D83CDF90"
          },
          {
            "\xD83C\xDF92",
            "D83CDF92"
          },
          {
            "\xD83C\xDF93",
            "D83CDF93"
          },
          {
            "\xD83C\xDFA3",
            "D83CDFA3"
          },
          {
            "\xD83C\xDFA4",
            "D83CDFA4"
          },
          {
            "\xD83C\xDFA7",
            "D83CDFA7"
          },
          {
            "\xD83C\xDFA8",
            "D83CDFA8"
          },
          {
            "\xD83C\xDFA9",
            "D83CDFA9"
          },
          {
            "\xD83C\xDFAB",
            "D83CDFAB"
          },
          {
            "\xD83C\xDFAC",
            "D83CDFAC"
          },
          {
            "\xD83C\xDFAD",
            "D83CDFAD"
          },
          {
            "\xD83C\xDFAF",
            "D83CDFAF"
          },
          {
            "\xD83C\xDFB0",
            "D83CDFB0"
          },
          {
            "\xD83C\xDFB3",
            "D83CDFB3"
          },
          {
            "\xD83C\xDFB4",
            "D83CDFB4"
          },
          {
            "\xD83C\xDFB9",
            "D83CDFB9"
          },
          {
            "\xD83C\xDFBA",
            "D83CDFBA"
          },
          {
            "\xD83C\xDFBB",
            "D83CDFBB"
          },
          {
            "\xD83C\xDFBD",
            "D83CDFBD"
          },
          {
            "\xD83C\xDFBF",
            "D83CDFBF"
          },
          {
            "\xD83C\xDFC2",
            "D83CDFC2"
          },
          {
            "\xD83C\xDFC3",
            "D83CDFC3"
          },
          {
            "\xD83C\xDFC4",
            "D83CDFC4"
          },
          {
            "\xD83C\xDFC7",
            "D83CDFC7"
          },
          {
            "\xD83C\xDFC8",
            "D83CDFC8"
          },
          {
            "\xD83C\xDFC9",
            "D83CDFC9"
          },
          {
            "\xD83C\xDFCA",
            "D83CDFCA"
          },
          {
            "\xD83D\xDC00",
            "D83DDC00"
          },
          {
            "\xD83D\xDC01",
            "D83DDC01"
          },
          {
            "\xD83D\xDC02",
            "D83DDC02"
          },
          {
            "\xD83D\xDC04",
            "D83DDC04"
          },
          {
            "\xD83D\xDC06",
            "D83DDC06"
          },
          {
            "\xD83D\xDC07",
            "D83DDC07"
          },
          {
            "\xD83D\xDC08",
            "D83DDC08"
          },
          {
            "\xD83D\xDC09",
            "D83DDC09"
          },
          {
            "\xD83D\xDC0A",
            "D83DDC0A"
          },
          {
            "\xD83D\xDC0B",
            "D83DDC0B"
          },
          {
            "\xD83D\xDC0C",
            "D83DDC0C"
          },
          {
            "\xD83D\xDC0D",
            "D83DDC0D"
          },
          {
            "\xD83D\xDC10",
            "D83DDC10"
          },
          {
            "\xD83D\xDC12",
            "D83DDC12"
          },
          {
            "\xD83D\xDC14",
            "D83DDC14"
          },
          {
            "\xD83D\xDC15",
            "D83DDC15"
          },
          {
            "\xD83D\xDC16",
            "D83DDC16"
          },
          {
            "\xD83D\xDC17",
            "D83DDC17"
          },
          {
            "\xD83D\xDC19",
            "D83DDC19"
          },
          {
            "\xD83D\xDC1A",
            "D83DDC1A"
          },
          {
            "\xD83D\xDC1B",
            "D83DDC1B"
          },
          {
            "\xD83D\xDC1D",
            "D83DDC1D"
          },
          {
            "\xD83D\xDC1E",
            "D83DDC1E"
          },
          {
            "\xD83D\xDC1F",
            "D83DDC1F"
          },
          {
            "\xD83D\xDC20",
            "D83DDC20"
          },
          {
            "\xD83D\xDC21",
            "D83DDC21"
          },
          {
            "\xD83D\xDC22",
            "D83DDC22"
          },
          {
            "\xD83D\xDC23",
            "D83DDC23"
          },
          {
            "\xD83D\xDC24",
            "D83DDC24"
          },
          {
            "\xD83D\xDC25",
            "D83DDC25"
          },
          {
            "\xD83D\xDC26",
            "D83DDC26"
          },
          {
            "\xD83D\xDC27",
            "D83DDC27"
          },
          {
            "\xD83D\xDC29",
            "D83DDC29"
          },
          {
            "\xD83D\xDC2A",
            "D83DDC2A"
          },
          {
            "\xD83D\xDC2C",
            "D83DDC2C"
          },
          {
            "\xD83D\xDC2D",
            "D83DDC2D"
          },
          {
            "\xD83D\xDC2F",
            "D83DDC2F"
          },
          {
            "\xD83D\xDC30",
            "D83DDC30"
          },
          {
            "\xD83D\xDC32",
            "D83DDC32"
          },
          {
            "\xD83D\xDC33",
            "D83DDC33"
          },
          {
            "\xD83D\xDC34",
            "D83DDC34"
          },
          {
            "\xD83D\xDC35",
            "D83DDC35"
          },
          {
            "\xD83D\xDC38",
            "D83DDC38"
          },
          {
            "\xD83D\xDC39",
            "D83DDC39"
          },
          {
            "\xD83D\xDC3A",
            "D83DDC3A"
          },
          {
            "\xD83D\xDC3D",
            "D83DDC3D"
          },
          {
            "\xD83D\xDC3E",
            "D83DDC3E"
          },
          {
            "\xD83D\xDC40",
            "D83DDC40"
          },
          {
            "\xD83D\xDC44",
            "D83DDC44"
          },
          {
            "\xD83D\xDC45",
            "D83DDC45"
          },
          {
            "\xD83D\xDC4B",
            "D83DDC4B"
          },
          {
            "\xD83D\xDC50",
            "D83DDC50"
          },
          {
            "\xD83D\xDC51",
            "D83DDC51"
          },
          {
            "\xD83D\xDC52",
            "D83DDC52"
          },
          {
            "\xD83D\xDC53",
            "D83DDC53"
          },
          {
            "\xD83D\xDC54",
            "D83DDC54"
          },
          {
            "\xD83D\xDC55",
            "D83DDC55"
          },
          {
            "\xD83D\xDC56",
            "D83DDC56"
          },
          {
            "\xD83D\xDC57",
            "D83DDC57"
          },
          {
            "\xD83D\xDC58",
            "D83DDC58"
          },
          {
            "\xD83D\xDC59",
            "D83DDC59"
          },
          {
            "\xD83D\xDC5A",
            "D83DDC5A"
          },
          {
            "\xD83D\xDC5B",
            "D83DDC5B"
          },
          {
            "\xD83D\xDC5C",
            "D83DDC5C"
          },
          {
            "\xD83D\xDC5D",
            "D83DDC5D"
          },
          {
            "\xD83D\xDC5E",
            "D83DDC5E"
          },
          {
            "\xD83D\xDC5F",
            "D83DDC5F"
          },
          {
            "\xD83D\xDC60",
            "D83DDC60"
          },
          {
            "\xD83D\xDC61",
            "D83DDC61"
          },
          {
            "\xD83D\xDC62",
            "D83DDC62"
          },
          {
            "\xD83D\xDC63",
            "D83DDC63"
          },
          {
            "\xD83D\xDC66",
            "D83DDC66"
          },
          {
            "\xD83D\xDC67",
            "D83DDC67"
          },
          {
            "\xD83D\xDC68",
            "D83DDC68"
          },
          {
            "\xD83D\xDC69",
            "D83DDC69"
          },
          {
            "\xD83D\xDC6A",
            "D83DDC6A"
          },
          {
            "\xD83D\xDC6B",
            "D83DDC6B"
          },
          {
            "\xD83D\xDC6C",
            "D83DDC6C"
          },
          {
            "\xD83D\xDC6D",
            "D83DDC6D"
          },
          {
            "\xD83D\xDC6E",
            "D83DDC6E"
          },
          {
            "\xD83D\xDC6F",
            "D83DDC6F"
          },
          {
            "\xD83D\xDC70",
            "D83DDC70"
          },
          {
            "\xD83D\xDC71",
            "D83DDC71"
          },
          {
            "\xD83D\xDC72",
            "D83DDC72"
          },
          {
            "\xD83D\xDC73",
            "D83DDC73"
          },
          {
            "\xD83D\xDC74",
            "D83DDC74"
          },
          {
            "\xD83D\xDC75",
            "D83DDC75"
          },
          {
            "\xD83D\xDC76",
            "D83DDC76"
          },
          {
            "\xD83D\xDC77",
            "D83DDC77"
          },
          {
            "\xD83D\xDC78",
            "D83DDC78"
          },
          {
            "\xD83D\xDC7B",
            "D83DDC7B"
          },
          {
            "\xD83D\xDC7C",
            "D83DDC7C"
          },
          {
            "\xD83D\xDC7E",
            "D83DDC7E"
          },
          {
            "\xD83D\xDC80",
            "D83DDC80"
          },
          {
            "\xD83D\xDC81",
            "D83DDC81"
          },
          {
            "\xD83D\xDC82",
            "D83DDC82"
          },
          {
            "\xD83D\xDC83",
            "D83DDC83"
          },
          {
            "\xD83D\xDC84",
            "D83DDC84"
          },
          {
            "\xD83D\xDC85",
            "D83DDC85"
          },
          {
            "\xD83D\xDC86",
            "D83DDC86"
          },
          {
            "\xD83D\xDC87",
            "D83DDC87"
          },
          {
            "\xD83D\xDC88",
            "D83DDC88"
          },
          {
            "\xD83D\xDC89",
            "D83DDC89"
          },
          {
            "\xD83D\xDC8A",
            "D83DDC8A"
          },
          {
            "\xD83D\xDC8C",
            "D83DDC8C"
          },
          {
            "\xD83D\xDC8D",
            "D83DDC8D"
          },
          {
            "\xD83D\xDC8E",
            "D83DDC8E"
          },
          {
            "\xD83D\xDC8F",
            "D83DDC8F"
          },
          {
            "\xD83D\xDC90",
            "D83DDC90"
          },
          {
            "\xD83D\xDC91",
            "D83DDC91"
          },
          {
            "\xD83D\xDC92",
            "D83DDC92"
          },
          {
            "\xD83D\xDC93",
            "D83DDC93"
          },
          {
            "\xD83D\xDC95",
            "D83DDC95"
          },
          {
            "\xD83D\xDC96",
            "D83DDC96"
          },
          {
            "\xD83D\xDC97",
            "D83DDC97"
          },
          {
            "\xD83D\xDC98",
            "D83DDC98"
          },
          {
            "\xD83D\xDC99",
            "D83DDC99"
          },
          {
            "\xD83D\xDC9A",
            "D83DDC9A"
          },
          {
            "\xD83D\xDC9B",
            "D83DDC9B"
          },
          {
            "\xD83D\xDC9C",
            "D83DDC9C"
          },
          {
            "\xD83D\xDC9D",
            "D83DDC9D"
          },
          {
            "\xD83D\xDC9E",
            "D83DDC9E"
          },
          {
            "\xD83D\xDC9F",
            "D83DDC9F"
          },
          {
            "\xD83D\xDCA1",
            "D83DDCA1"
          },
          {
            "\xD83D\xDCA3",
            "D83DDCA3"
          },
          {
            "\xD83D\xDCA5",
            "D83DDCA5"
          },
          {
            "\xD83D\xDCA7",
            "D83DDCA7"
          },
          {
            "\xD83D\xDCA8",
            "D83DDCA8"
          },
          {
            "\xD83D\xDCAC",
            "D83DDCAC"
          },
          {
            "\xD83D\xDCB0",
            "D83DDCB0"
          },
          {
            "\xD83D\xDCB3",
            "D83DDCB3"
          },
          {
            "\xD83D\xDCB4",
            "D83DDCB4"
          },
          {
            "\xD83D\xDCB5",
            "D83DDCB5"
          },
          {
            "\xD83D\xDCB6",
            "D83DDCB6"
          },
          {
            "\xD83D\xDCB7",
            "D83DDCB7"
          },
          {
            "\xD83D\xDCB8",
            "D83DDCB8"
          },
          {
            "\xD83D\xDCBA",
            "D83DDCBA"
          },
          {
            "\xD83D\xDCBB",
            "D83DDCBB"
          },
          {
            "\xD83D\xDCBC",
            "D83DDCBC"
          },
          {
            "\xD83D\xDCBD",
            "D83DDCBD"
          },
          {
            "\xD83D\xDCBE",
            "D83DDCBE"
          },
          {
            "\xD83D\xDCBF",
            "D83DDCBF"
          },
          {
            "\xD83D\xDCC4",
            "D83DDCC4"
          },
          {
            "\xD83D\xDCC5",
            "D83DDCC5"
          },
          {
            "\xD83D\xDCC7",
            "D83DDCC7"
          },
          {
            "\xD83D\xDCC8",
            "D83DDCC8"
          },
          {
            "\xD83D\xDCC9",
            "D83DDCC9"
          },
          {
            "\xD83D\xDCCA",
            "D83DDCCA"
          },
          {
            "\xD83D\xDCCB",
            "D83DDCCB"
          },
          {
            "\xD83D\xDCCC",
            "D83DDCCC"
          },
          {
            "\xD83D\xDCCD",
            "D83DDCCD"
          },
          {
            "\xD83D\xDCCE",
            "D83DDCCE"
          },
          {
            "\xD83D\xDCD0",
            "D83DDCD0"
          },
          {
            "\xD83D\xDCD1",
            "D83DDCD1"
          },
          {
            "\xD83D\xDCD2",
            "D83DDCD2"
          },
          {
            "\xD83D\xDCD3",
            "D83DDCD3"
          },
          {
            "\xD83D\xDCD4",
            "D83DDCD4"
          },
          {
            "\xD83D\xDCD5",
            "D83DDCD5"
          },
          {
            "\xD83D\xDCD6",
            "D83DDCD6"
          },
          {
            "\xD83D\xDCD7",
            "D83DDCD7"
          },
          {
            "\xD83D\xDCD8",
            "D83DDCD8"
          },
          {
            "\xD83D\xDCD9",
            "D83DDCD9"
          },
          {
            "\xD83D\xDCDA",
            "D83DDCDA"
          },
          {
            "\xD83D\xDCDC",
            "D83DDCDC"
          },
          {
            "\xD83D\xDCDD",
            "D83DDCDD"
          },
          {
            "\xD83D\xDCDF",
            "D83DDCDF"
          },
          {
            "\xD83D\xDCE0",
            "D83DDCE0"
          },
          {
            "\xD83D\xDCE1",
            "D83DDCE1"
          },
          {
            "\xD83D\xDCE2",
            "D83DDCE2"
          },
          {
            "\xD83D\xDCE6",
            "D83DDCE6"
          },
          {
            "\xD83D\xDCED",
            "D83DDCED"
          },
          {
            "\xD83D\xDCEE",
            "D83DDCEE"
          },
          {
            "\xD83D\xDCEF",
            "D83DDCEF"
          },
          {
            "\xD83D\xDCF0",
            "D83DDCF0"
          },
          {
            "\xD83D\xDCF1",
            "D83DDCF1"
          },
          {
            "\xD83D\xDCF7",
            "D83DDCF7"
          },
          {
            "\xD83D\xDCF9",
            "D83DDCF9"
          },
          {
            "\xD83D\xDCFA",
            "D83DDCFA"
          },
          {
            "\xD83D\xDCFB",
            "D83DDCFB"
          },
          {
            "\xD83D\xDCFC",
            "D83DDCFC"
          },
          {
            "\xD83D\xDD06",
            "D83DDD06"
          },
          {
            "\xD83D\xDD0E",
            "D83DDD0E"
          },
          {
            "\xD83D\xDD11",
            "D83DDD11"
          },
          {
            "\xD83D\xDD14",
            "D83DDD14"
          },
          {
            "\xD83D\xDD16",
            "D83DDD16"
          },
          {
            "\xD83D\xDD25",
            "D83DDD25"
          },
          {
            "\xD83D\xDD26",
            "D83DDD26"
          },
          {
            "\xD83D\xDD27",
            "D83DDD27"
          },
          {
            "\xD83D\xDD28",
            "D83DDD28"
          },
          {
            "\xD83D\xDD29",
            "D83DDD29"
          },
          {
            "\xD83D\xDD2A",
            "D83DDD2A"
          },
          {
            "\xD83D\xDD2B",
            "D83DDD2B"
          },
          {
            "\xD83D\xDD2C",
            "D83DDD2C"
          },
          {
            "\xD83D\xDD2D",
            "D83DDD2D"
          },
          {
            "\xD83D\xDD2E",
            "D83DDD2E"
          },
          {
            "\xD83D\xDD31",
            "D83DDD31"
          },
          {
            "\xD83D\xDDFF",
            "D83DDDFF"
          },
          {
            "\xD83D\xDE45",
            "D83DDE45"
          },
          {
            "\xD83D\xDE46",
            "D83DDE46"
          },
          {
            "\xD83D\xDE47",
            "D83DDE47"
          },
          {
            "\xD83D\xDE48",
            "D83DDE48"
          },
          {
            "\xD83D\xDE49",
            "D83DDE49"
          },
          {
            "\xD83D\xDE4A",
            "D83DDE4A"
          },
          {
            "\xD83D\xDE4B",
            "D83DDE4B"
          },
          {
            "\xD83D\xDE4C",
            "D83DDE4C"
          },
          {
            "\xD83D\xDE4E",
            "D83DDE4E"
          },
          {
            "\xD83D\xDE80",
            "D83DDE80"
          },
          {
            "\xD83D\xDE81",
            "D83DDE81"
          },
          {
            "\xD83D\xDE82",
            "D83DDE82"
          },
          {
            "\xD83D\xDE83",
            "D83DDE83"
          },
          {
            "\xD83D\xDE84",
            "D83DDE84"
          },
          {
            "\xD83D\xDE85",
            "D83DDE85"
          },
          {
            "\xD83D\xDE86",
            "D83DDE86"
          },
          {
            "\xD83D\xDE87",
            "D83DDE87"
          },
          {
            "\xD83D\xDE88",
            "D83DDE88"
          },
          {
            "\xD83D\xDE8A",
            "D83DDE8A"
          },
          {
            "\xD83D\xDE8C",
            "D83DDE8C"
          },
          {
            "\xD83D\xDE8D",
            "D83DDE8D"
          },
          {
            "\xD83D\xDE8E",
            "D83DDE8E"
          },
          {
            "\xD83D\xDE8F",
            "D83DDE8F"
          },
          {
            "\xD83D\xDE90",
            "D83DDE90"
          },
          {
            "\xD83D\xDE91",
            "D83DDE91"
          },
          {
            "\xD83D\xDE92",
            "D83DDE92"
          },
          {
            "\xD83D\xDE93",
            "D83DDE93"
          },
          {
            "\xD83D\xDE94",
            "D83DDE94"
          },
          {
            "\xD83D\xDE95",
            "D83DDE95"
          },
          {
            "\xD83D\xDE96",
            "D83DDE96"
          },
          {
            "\xD83D\xDE97",
            "D83DDE97"
          },
          {
            "\xD83D\xDE98",
            "D83DDE98"
          },
          {
            "\xD83D\xDE99",
            "D83DDE99"
          },
          {
            "\xD83D\xDE9A",
            "D83DDE9A"
          },
          {
            "\xD83D\xDE9B",
            "D83DDE9B"
          },
          {
            "\xD83D\xDE9C",
            "D83DDE9C"
          },
          {
            "\xD83D\xDE9D",
            "D83DDE9D"
          },
          {
            "\xD83D\xDE9E",
            "D83DDE9E"
          },
          {
            "\xD83D\xDE9F",
            "D83DDE9F"
          },
          {
            "\xD83D\xDEA0",
            "D83DDEA0"
          },
          {
            "\xD83D\xDEA1",
            "D83DDEA1"
          },
          {
            "\xD83D\xDEA3",
            "D83DDEA3"
          },
          {
            "\xD83D\xDEA4",
            "D83DDEA4"
          },
          {
            "\xD83D\xDEA7",
            "D83DDEA7"
          },
          {
            "\xD83D\xDEA8",
            "D83DDEA8"
          },
          {
            "\xD83D\xDEAA",
            "D83DDEAA"
          },
          {
            "\xD83D\xDEAC",
            "D83DDEAC"
          },
          {
            "\xD83D\xDEB4",
            "D83DDEB4"
          },
          {
            "\xD83D\xDEB5",
            "D83DDEB5"
          },
          {
            "\xD83D\xDEB6",
            "D83DDEB6"
          },
          {
            "\xD83D\xDEBD",
            "D83DDEBD"
          },
          {
            "\xD83D\xDEBF",
            "D83DDEBF"
          },
          {
            "\xD83D\xDEC0",
            "D83DDEC0"
          },
          {
            "\xD83C\xDDE8\xD83C\xDDF3",
            "D83CDDE8D83CDDF3"
          },
          {
            "\xD83C\xDDE9\xD83C\xDDEA",
            "D83CDDE9D83CDDEA"
          },
          {
            "\xD83C\xDDEA\xD83C\xDDF8",
            "D83CDDEAD83CDDF8"
          },
          {
            "\xD83C\xDDEB\xD83C\xDDF7",
            "D83CDDEBD83CDDF7"
          },
          {
            "\xD83C\xDDEC\xD83C\xDDE7",
            "D83CDDECD83CDDE7"
          },
          {
            "\xD83C\xDDEE\xD83C\xDDF9",
            "D83CDDEED83CDDF9"
          },
          {
            "\xD83C\xDDEF\xD83C\xDDF5",
            "D83CDDEFD83CDDF5"
          },
          {
            "\xD83C\xDDF0\xD83C\xDDF7",
            "D83CDDF0D83CDDF7"
          },
          {
            "\xD83C\xDDF7\xD83C\xDDFA",
            "D83CDDF7D83CDDFA"
          },
          {
            "\xD83C\xDDFA\xD83C\xDDF8",
            "D83CDDFAD83CDDF8"
          },
          {
            "\xD83D\xDD30",
            "D83DDD30"
          },
          {
            "#⃣",
            "002320E3"
          },
          {
            "0⃣",
            "003020E3"
          },
          {
            "1⃣",
            "003120E3"
          },
          {
            "2⃣",
            "003220E3"
          },
          {
            "3⃣",
            "003320E3"
          },
          {
            "4⃣",
            "003420E3"
          },
          {
            "5⃣",
            "003520E3"
          },
          {
            "6⃣",
            "003620E3"
          },
          {
            "7⃣",
            "003720E3"
          },
          {
            "8⃣",
            "003820E3"
          },
          {
            "9⃣",
            "003920E3"
          },
          {
            "©",
            "00A9"
          },
          {
            "®",
            "00AE"
          },
          {
            "‼",
            "203C"
          },
          {
            "⁉",
            "2049"
          },
          {
            "™",
            "2122"
          },
          {
            "ℹ",
            "2139"
          },
          {
            "↔",
            "2194"
          },
          {
            "↕",
            "2195"
          },
          {
            "↖",
            "2196"
          },
          {
            "↗",
            "2197"
          },
          {
            "↘",
            "2198"
          },
          {
            "↙",
            "2199"
          },
          {
            "↩",
            "21A9"
          },
          {
            "↪",
            "21AA"
          },
          {
            "⌚",
            "231A"
          },
          {
            "⌛",
            "231B"
          },
          {
            "⏩",
            "23E9"
          },
          {
            "⏪",
            "23EA"
          },
          {
            "⏫",
            "23EB"
          },
          {
            "⏬",
            "23EC"
          },
          {
            "Ⓜ",
            "24C2"
          },
          {
            "▪",
            "25AA"
          },
          {
            "▫",
            "25AB"
          },
          {
            "▶",
            "25B6"
          },
          {
            "◀",
            "25C0"
          },
          {
            "◻",
            "25FB"
          },
          {
            "◼",
            "25FC"
          },
          {
            "◽",
            "25FD"
          },
          {
            "◾",
            "25FE"
          },
          {
            "☑",
            "2611"
          },
          {
            "☔",
            "2614"
          },
          {
            "♈",
            "2648"
          },
          {
            "♉",
            "2649"
          },
          {
            "♊",
            "264A"
          },
          {
            "♋",
            "264B"
          },
          {
            "♌",
            "264C"
          },
          {
            "♍",
            "264D"
          },
          {
            "♎",
            "264E"
          },
          {
            "♏",
            "264F"
          },
          {
            "♐",
            "2650"
          },
          {
            "♑",
            "2651"
          },
          {
            "♒",
            "2652"
          },
          {
            "♓",
            "2653"
          },
          {
            "♠",
            "2660"
          },
          {
            "♣",
            "2663"
          },
          {
            "♥",
            "2665"
          },
          {
            "♦",
            "2666"
          },
          {
            "♨",
            "2668"
          },
          {
            "♿",
            "267F"
          },
          {
            "⚓",
            "2693"
          },
          {
            "⚪",
            "26AA"
          },
          {
            "⚫",
            "26AB"
          },
          {
            "⛎",
            "26CE"
          },
          {
            "⛲",
            "26F2"
          },
          {
            "⛺",
            "26FA"
          },
          {
            "✅",
            "2705"
          },
          {
            "✔",
            "2714"
          },
          {
            "✖",
            "2716"
          },
          {
            "✳",
            "2733"
          },
          {
            "✴",
            "2734"
          },
          {
            "❇",
            "2747"
          },
          {
            "❌",
            "274C"
          },
          {
            "❎",
            "274E"
          },
          {
            "❓",
            "2753"
          },
          {
            "❔",
            "2754"
          },
          {
            "❕",
            "2755"
          },
          {
            "❗",
            "2757"
          },
          {
            "➕",
            "2795"
          },
          {
            "➖",
            "2796"
          },
          {
            "➗",
            "2797"
          },
          {
            "➡",
            "27A1"
          },
          {
            "➰",
            "27B0"
          },
          {
            "➿",
            "27BF"
          },
          {
            "⤴",
            "2934"
          },
          {
            "⤵",
            "2935"
          },
          {
            "⬅",
            "2B05"
          },
          {
            "⬆",
            "2B06"
          },
          {
            "⬇",
            "2B07"
          },
          {
            "⬛",
            "2B1B"
          },
          {
            "⬜",
            "2B1C"
          },
          {
            "⭐",
            "2B50"
          },
          {
            "⭕",
            "2B55"
          },
          {
            "〰",
            "3030"
          },
          {
            "〽",
            "303D"
          },
          {
            "\xD83C\xDD70",
            "D83CDD70"
          },
          {
            "\xD83C\xDD71",
            "D83CDD71"
          },
          {
            "\xD83C\xDD7E",
            "D83CDD7E"
          },
          {
            "\xD83C\xDD7F",
            "D83CDD7F"
          },
          {
            "\xD83C\xDD8E",
            "D83CDD8E"
          },
          {
            "\xD83C\xDD91",
            "D83CDD91"
          },
          {
            "\xD83C\xDD92",
            "D83CDD92"
          },
          {
            "\xD83C\xDD93",
            "D83CDD93"
          },
          {
            "\xD83C\xDD94",
            "D83CDD94"
          },
          {
            "\xD83C\xDD95",
            "D83CDD95"
          },
          {
            "\xD83C\xDD96",
            "D83CDD96"
          },
          {
            "\xD83C\xDD97",
            "D83CDD97"
          },
          {
            "\xD83C\xDD99",
            "D83CDD99"
          },
          {
            "\xD83C\xDD9A",
            "D83CDD9A"
          },
          {
            "\xD83C\xDE01",
            "D83CDE01"
          },
          {
            "\xD83C\xDF00",
            "D83CDF00"
          },
          {
            "\xD83C\xDF01",
            "D83CDF01"
          },
          {
            "\xD83C\xDF03",
            "D83CDF03"
          },
          {
            "\xD83C\xDF04",
            "D83CDF04"
          },
          {
            "\xD83C\xDF05",
            "D83CDF05"
          },
          {
            "\xD83C\xDF06",
            "D83CDF06"
          },
          {
            "\xD83C\xDF07",
            "D83CDF07"
          },
          {
            "\xD83C\xDF08",
            "D83CDF08"
          },
          {
            "\xD83C\xDF09",
            "D83CDF09"
          },
          {
            "\xD83C\xDF0A",
            "D83CDF0A"
          },
          {
            "\xD83C\xDF0B",
            "D83CDF0B"
          },
          {
            "\xD83C\xDF0C",
            "D83CDF0C"
          },
          {
            "\xD83C\xDF0E",
            "D83CDF0E"
          },
          {
            "\xD83C\xDF0F",
            "D83CDF0F"
          },
          {
            "\xD83C\xDF10",
            "D83CDF10"
          },
          {
            "\xD83C\xDF11",
            "D83CDF11"
          },
          {
            "\xD83C\xDF12",
            "D83CDF12"
          },
          {
            "\xD83C\xDF13",
            "D83CDF13"
          },
          {
            "\xD83C\xDF14",
            "D83CDF14"
          },
          {
            "\xD83C\xDF15",
            "D83CDF15"
          },
          {
            "\xD83C\xDF16",
            "D83CDF16"
          },
          {
            "\xD83C\xDF17",
            "D83CDF17"
          },
          {
            "\xD83C\xDF18",
            "D83CDF18"
          },
          {
            "\xD83C\xDF19",
            "D83CDF19"
          },
          {
            "\xD83C\xDF1A",
            "D83CDF1A"
          },
          {
            "\xD83C\xDF1C",
            "D83CDF1C"
          },
          {
            "\xD83C\xDF20",
            "D83CDF20"
          },
          {
            "\xD83C\xDF58",
            "D83CDF58"
          },
          {
            "\xD83C\xDF59",
            "D83CDF59"
          },
          {
            "\xD83C\xDF86",
            "D83CDF86"
          },
          {
            "\xD83C\xDF87",
            "D83CDF87"
          },
          {
            "\xD83C\xDF91",
            "D83CDF91"
          },
          {
            "\xD83C\xDFA0",
            "D83CDFA0"
          },
          {
            "\xD83C\xDFA1",
            "D83CDFA1"
          },
          {
            "\xD83C\xDFA2",
            "D83CDFA2"
          },
          {
            "\xD83C\xDFA5",
            "D83CDFA5"
          },
          {
            "\xD83C\xDFA6",
            "D83CDFA6"
          },
          {
            "\xD83C\xDFAE",
            "D83CDFAE"
          },
          {
            "\xD83C\xDFB5",
            "D83CDFB5"
          },
          {
            "\xD83C\xDFB6",
            "D83CDFB6"
          },
          {
            "\xD83C\xDFBC",
            "D83CDFBC"
          },
          {
            "\xD83C\xDFE0",
            "D83CDFE0"
          },
          {
            "\xD83C\xDFE1",
            "D83CDFE1"
          },
          {
            "\xD83C\xDFE2",
            "D83CDFE2"
          },
          {
            "\xD83C\xDFE3",
            "D83CDFE3"
          },
          {
            "\xD83C\xDFE4",
            "D83CDFE4"
          },
          {
            "\xD83C\xDFE5",
            "D83CDFE5"
          },
          {
            "\xD83C\xDFE7",
            "D83CDFE7"
          },
          {
            "\xD83C\xDFE8",
            "D83CDFE8"
          },
          {
            "\xD83C\xDFE9",
            "D83CDFE9"
          },
          {
            "\xD83C\xDFEA",
            "D83CDFEA"
          },
          {
            "\xD83C\xDFEB",
            "D83CDFEB"
          },
          {
            "\xD83C\xDFEC",
            "D83CDFEC"
          },
          {
            "\xD83C\xDFED",
            "D83CDFED"
          },
          {
            "\xD83C\xDFEE",
            "D83CDFEE"
          },
          {
            "\xD83C\xDFEF",
            "D83CDFEF"
          },
          {
            "\xD83C\xDFF0",
            "D83CDFF0"
          },
          {
            "\xD83D\xDC49",
            "D83DDC49"
          },
          {
            "\xD83D\xDC64",
            "D83DDC64"
          },
          {
            "\xD83D\xDC65",
            "D83DDC65"
          },
          {
            "\xD83D\xDCA0",
            "D83DDCA0"
          },
          {
            "\xD83D\xDCA2",
            "D83DDCA2"
          },
          {
            "\xD83D\xDCA4",
            "D83DDCA4"
          },
          {
            "\xD83D\xDCAB",
            "D83DDCAB"
          },
          {
            "\xD83D\xDCAE",
            "D83DDCAE"
          },
          {
            "\xD83D\xDCAF",
            "D83DDCAF"
          },
          {
            "\xD83D\xDCB1",
            "D83DDCB1"
          },
          {
            "\xD83D\xDCB2",
            "D83DDCB2"
          },
          {
            "\xD83D\xDCB9",
            "D83DDCB9"
          },
          {
            "\xD83D\xDCC0",
            "D83DDCC0"
          },
          {
            "\xD83D\xDCC1",
            "D83DDCC1"
          },
          {
            "\xD83D\xDCC2",
            "D83DDCC2"
          },
          {
            "\xD83D\xDCC3",
            "D83DDCC3"
          },
          {
            "\xD83D\xDCC6",
            "D83DDCC6"
          },
          {
            "\xD83D\xDCCF",
            "D83DDCCF"
          },
          {
            "\xD83D\xDCDB",
            "D83DDCDB"
          },
          {
            "\xD83D\xDCDE",
            "D83DDCDE"
          },
          {
            "\xD83D\xDCE3",
            "D83DDCE3"
          },
          {
            "\xD83D\xDCE4",
            "D83DDCE4"
          },
          {
            "\xD83D\xDCE5",
            "D83DDCE5"
          },
          {
            "\xD83D\xDCE7",
            "D83DDCE7"
          },
          {
            "\xD83D\xDCE8",
            "D83DDCE8"
          },
          {
            "\xD83D\xDCE9",
            "D83DDCE9"
          },
          {
            "\xD83D\xDCEA",
            "D83DDCEA"
          },
          {
            "\xD83D\xDCEB",
            "D83DDCEB"
          },
          {
            "\xD83D\xDCEC",
            "D83DDCEC"
          },
          {
            "\xD83D\xDCF2",
            "D83DDCF2"
          },
          {
            "\xD83D\xDCF3",
            "D83DDCF3"
          },
          {
            "\xD83D\xDCF4",
            "D83DDCF4"
          },
          {
            "\xD83D\xDCF5",
            "D83DDCF5"
          },
          {
            "\xD83D\xDCF6",
            "D83DDCF6"
          },
          {
            "\xD83D\xDD00",
            "D83DDD00"
          },
          {
            "\xD83D\xDD01",
            "D83DDD01"
          },
          {
            "\xD83D\xDD02",
            "D83DDD02"
          },
          {
            "\xD83D\xDD03",
            "D83DDD03"
          },
          {
            "\xD83D\xDD04",
            "D83DDD04"
          },
          {
            "\xD83D\xDD05",
            "D83DDD05"
          },
          {
            "\xD83D\xDD07",
            "D83DDD07"
          },
          {
            "\xD83D\xDD08",
            "D83DDD08"
          },
          {
            "\xD83D\xDD09",
            "D83DDD09"
          },
          {
            "\xD83D\xDD0A",
            "D83DDD0A"
          },
          {
            "\xD83D\xDD0B",
            "D83DDD0B"
          },
          {
            "\xD83D\xDD0C",
            "D83DDD0C"
          },
          {
            "\xD83D\xDD0D",
            "D83DDD0D"
          },
          {
            "\xD83D\xDD0F",
            "D83DDD0F"
          },
          {
            "\xD83D\xDD10",
            "D83DDD10"
          },
          {
            "\xD83D\xDD12",
            "D83DDD12"
          },
          {
            "\xD83D\xDD13",
            "D83DDD13"
          },
          {
            "\xD83D\xDD15",
            "D83DDD15"
          },
          {
            "\xD83D\xDD17",
            "D83DDD17"
          },
          {
            "\xD83D\xDD18",
            "D83DDD18"
          },
          {
            "\xD83D\xDD19",
            "D83DDD19"
          },
          {
            "\xD83D\xDD1A",
            "D83DDD1A"
          },
          {
            "\xD83D\xDD1B",
            "D83DDD1B"
          },
          {
            "\xD83D\xDD1C",
            "D83DDD1C"
          },
          {
            "\xD83D\xDD1D",
            "D83DDD1D"
          },
          {
            "\xD83D\xDD1F",
            "D83DDD1F"
          },
          {
            "\xD83D\xDD20",
            "D83DDD20"
          },
          {
            "\xD83D\xDD21",
            "D83DDD21"
          },
          {
            "\xD83D\xDD22",
            "D83DDD22"
          },
          {
            "\xD83D\xDD23",
            "D83DDD23"
          },
          {
            "\xD83D\xDD24",
            "D83DDD24"
          },
          {
            "\xD83D\xDD2F",
            "D83DDD2F"
          },
          {
            "\xD83D\xDD32",
            "D83DDD32"
          },
          {
            "\xD83D\xDD33",
            "D83DDD33"
          },
          {
            "\xD83D\xDD34",
            "D83DDD34"
          },
          {
            "\xD83D\xDD35",
            "D83DDD35"
          },
          {
            "\xD83D\xDD36",
            "D83DDD36"
          },
          {
            "\xD83D\xDD37",
            "D83DDD37"
          },
          {
            "\xD83D\xDD38",
            "D83DDD38"
          },
          {
            "\xD83D\xDD39",
            "D83DDD39"
          },
          {
            "\xD83D\xDD3A",
            "D83DDD3A"
          },
          {
            "\xD83D\xDD3B",
            "D83DDD3B"
          },
          {
            "\xD83D\xDD3C",
            "D83DDD3C"
          },
          {
            "\xD83D\xDD3D",
            "D83DDD3D"
          },
          {
            "\xD83D\xDDFB",
            "D83DDDFB"
          },
          {
            "\xD83D\xDDFC",
            "D83DDDFC"
          },
          {
            "\xD83D\xDDFD",
            "D83DDDFD"
          },
          {
            "\xD83D\xDDFE",
            "D83DDDFE"
          },
          {
            "\xD83D\xDE17",
            "D83DDE17"
          },
          {
            "\xD83D\xDE4D",
            "D83DDE4D"
          },
          {
            "\xD83D\xDE89",
            "D83DDE89"
          },
          {
            "\xD83D\xDE8B",
            "D83DDE8B"
          },
          {
            "\xD83D\xDEA2",
            "D83DDEA2"
          },
          {
            "\xD83D\xDEA5",
            "D83DDEA5"
          },
          {
            "\xD83D\xDEA6",
            "D83DDEA6"
          },
          {
            "\xD83D\xDEA9",
            "D83DDEA9"
          },
          {
            "\xD83D\xDEAB",
            "D83DDEAB"
          },
          {
            "\xD83D\xDEAD",
            "D83DDEAD"
          },
          {
            "\xD83D\xDEAE",
            "D83DDEAE"
          },
          {
            "\xD83D\xDEAF",
            "D83DDEAF"
          },
          {
            "\xD83D\xDEB0",
            "D83DDEB0"
          },
          {
            "\xD83D\xDEB1",
            "D83DDEB1"
          },
          {
            "\xD83D\xDEB2",
            "D83DDEB2"
          },
          {
            "\xD83D\xDEB3",
            "D83DDEB3"
          },
          {
            "\xD83D\xDEB7",
            "D83DDEB7"
          },
          {
            "\xD83D\xDEB8",
            "D83DDEB8"
          },
          {
            "\xD83D\xDEB9",
            "D83DDEB9"
          },
          {
            "\xD83D\xDEBA",
            "D83DDEBA"
          },
          {
            "\xD83D\xDEBB",
            "D83DDEBB"
          },
          {
            "\xD83D\xDEBC",
            "D83DDEBC"
          },
          {
            "\xD83D\xDEBE",
            "D83DDEBE"
          },
          {
            "\xD83D\xDEC1",
            "D83DDEC1"
          },
          {
            "\xD83D\xDEC2",
            "D83DDEC2"
          },
          {
            "\xD83D\xDEC3",
            "D83DDEC3"
          },
          {
            "\xD83D\xDEC4",
            "D83DDEC4"
          },
          {
            "\xD83D\xDEC5",
            "D83DDEC5"
          },
          {
            "☺️",
            "263A"
          },
          {
            "✌️",
            "270C"
          },
          {
            "☝️",
            "261D"
          },
          {
            "❤️",
            "2764"
          },
          {
            "⭐️",
            "2B50"
          },
          {
            "☀️",
            "2600"
          },
          {
            "☁️",
            "2601"
          },
          {
            "⚡️",
            "26A1"
          },
          {
            "☔️",
            "2614"
          },
          {
            "❄️",
            "2744"
          },
          {
            "☎️",
            "260E"
          },
          {
            "⌛️",
            "231B"
          },
          {
            "⌚️",
            "231A"
          },
          {
            "✉️",
            "2709"
          },
          {
            "✂️",
            "2702"
          },
          {
            "✒️",
            "2712"
          },
          {
            "✏️",
            "270F"
          },
          {
            "\xD83C\xDC04️",
            "D83CDC04"
          },
          {
            "☕️",
            "2615"
          },
          {
            "⚓️",
            "2693"
          },
          {
            "✈️",
            "2708"
          },
          {
            "⚠️",
            "26A0"
          },
          {
            "♨️",
            "2668"
          },
          {
            "⬆️",
            "2B06"
          },
          {
            "⬇️",
            "2B07"
          },
          {
            "⬅️",
            "2B05"
          },
          {
            "➡️",
            "27A1"
          },
          {
            "↗️",
            "2197"
          },
          {
            "↖️",
            "2196"
          },
          {
            "↘️",
            "2198"
          },
          {
            "↙️",
            "2199"
          },
          {
            "↔️",
            "2194"
          },
          {
            "↕️",
            "2195"
          },
          {
            "◀️",
            "25C0"
          },
          {
            "▶️",
            "25B6"
          },
          {
            "↩️",
            "21A9"
          },
          {
            "↪️",
            "21AA"
          },
          {
            "⤵️",
            "2935"
          },
          {
            "⤴️",
            "2934"
          },
          {
            "♿️",
            "267F"
          },
          {
            "Ⓜ️",
            "24C2"
          }
        };
    }
}
